In [ ]:
import pandas as pd

Series()

In [ ]:
s = pd.Series([6,34,23,56,43])
s

0     6
1    34
2    23
3    56
4    43
dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([ 6, 34, 23, 56, 43])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
print(s.name)

None

In [ ]:
s.name = 'Sample Series'
s

0     6
1    34
2    23
3    56
4    43
Name: Sample Series, dtype: int64

In [ ]:
s[0:3]

0     6
1    34
2    23
Name: Sample Series, dtype: int64

# iloc[ ]   -> Location Based Indexing

In [ ]:
s.iloc[0:3]

0     6
1    34
2    23
Name: Sample Series, dtype: int64

In [ ]:
s.name = 'calories table'
s

0     6
1    34
2    23
3    56
4    43
Name: calories table, dtype: int64

In [ ]:
i = ['Apple','Banana','Mango','Guava',"Watermelon"]
s.index = i
s

Apple          6
Banana        34
Mango         23
Guava         56
Watermelon    43
Name: calories table, dtype: int64

In [ ]:
s.iloc[0:3]

Apple      6
Banana    34
Mango     23
Name: calories table, dtype: int64

In [ ]:
s

Apple          6
Banana        34
Mango         23
Guava         56
Watermelon    43
Name: calories table, dtype: int64

# loc [ ] -> Label Based Location

In [ ]:
s.loc['Banana':'Watermelon']

Banana        34
Mango         23
Guava         56
Watermelon    43
Name: calories table, dtype: int64

# **Series By Dictionary**

In [ ]:
s1 = pd.Series({'LED TV': 12000,'AC': 25000,'Washing Machine': 14000,'Refrigerator': 19000,'Fan': 2500,'LED Light': 800,'Sofa': 28000 },name = 'Price')
s1

LED TV             12000
AC                 25000
Washing Machine    14000
Refrigerator       19000
Fan                 2500
LED Light            800
Sofa               28000
Name: Price, dtype: int64

In [ ]:
s1.name

'Price'

# Conditional Statement

In [ ]:
s1[(s1<15000) & (s1>10000)]

LED TV             12000
Washing Machine    14000
Name: Price, dtype: int64

In [ ]:
s1["Sofa"] = 35000
s1

LED TV             12000
AC                 25000
Washing Machine    14000
Refrigerator       19000
Fan                 2500
LED Light            800
Sofa               35000
Name: Price, dtype: int64

In [ ]:
print(s1.is_unique)

True

In [ ]:
import numpy as np

# **Dataframe**

In [ ]:
data ={
    'Name': ['Raj','Alone','Bob','Kamal','Geetha','Steve','Lalith'],
    'Experiance': [10,5,np.nan,1,2,7,5],
    'Salary' : [120000,45000,55000,25000,np.nan,60000,20000],
    'Role': ['ML Engineer','Software Engineer','Software Engineer','ML Engineer','HR','HR','Data Scientist']
    }


print(data)

{'Name': ['Raj', 'Alone', 'Bob', 'Kamal', 'Geetha', 'Steve', 'Lalith'], 'Experiance': [10, 5, nan, 1, 2, 7, 5], 'Salary': [120000, 45000, 55000, 25000, nan, 60000, 20000], 'Role': ['ML Engineer', 'Software Engineer', 'Software Engineer', 'ML Engineer', 'HR', 'HR', 'Data Scientist']}

In [ ]:
df = pd.DataFrame(data)
df

     Name  Experiance    Salary               Role
0     Raj        10.0  120000.0        ML Engineer
1   Alone         5.0   45000.0  Software Engineer
2     Bob         NaN   55000.0  Software Engineer
3   Kamal         1.0   25000.0        ML Engineer
4  Geetha         2.0       NaN                 HR
5   Steve         7.0   60000.0                 HR
6  Lalith         5.0   20000.0     Data Scientist

In [ ]:
df.head(2)

    Name  Experiance    Salary               Role
0    Raj        10.0  120000.0        ML Engineer
1  Alone         5.0   45000.0  Software Engineer

In [ ]:
df.tail(2)

     Name  Experiance   Salary            Role
5   Steve         7.0  60000.0              HR
6  Lalith         5.0  20000.0  Data Scientist

In [ ]:
df.loc[0:2,'Name':'Salary']

    Name  Experiance    Salary
0    Raj        10.0  120000.0
1  Alone         5.0   45000.0
2    Bob         NaN   55000.0

In [ ]:
df.iloc[0:3,1:3]

   Experiance    Salary
0        10.0  120000.0
1         5.0   45000.0
2         NaN   55000.0

In [ ]:
df[['Name','Salary']]

     Name    Salary
0     Raj  120000.0
1   Alone   45000.0
2     Bob   55000.0
3   Kamal   25000.0
4  Geetha       NaN
5   Steve   60000.0
6  Lalith   20000.0

In [ ]:
df.drop('Experiance',axis = 1)

     Name    Salary               Role
0     Raj  120000.0        ML Engineer
1   Alone   45000.0  Software Engineer
2     Bob   55000.0  Software Engineer
3   Kamal   25000.0        ML Engineer
4  Geetha       NaN                 HR
5   Steve   60000.0                 HR
6  Lalith   20000.0     Data Scientist

In [ ]:
df

     Name  Experiance    Salary               Role
0     Raj        10.0  120000.0        ML Engineer
1   Alone         5.0   45000.0  Software Engineer
2     Bob         NaN   55000.0  Software Engineer
3   Kamal         1.0   25000.0        ML Engineer
4  Geetha         2.0       NaN                 HR
5   Steve         7.0   60000.0                 HR
6  Lalith         5.0   20000.0     Data Scientist

In [ ]:
df.shape

(7, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        7 non-null      object
 1   Experiance  6 non-null      float64
 2   Salary      6 non-null      float64
 3   Role        7 non-null      object
dtypes: float64(2), object(2)
memory usage: 356.0+ bytes

In [ ]:
df.describe()

       Experiance         Salary
count    6.000000       6.000000
mean     5.000000   54166.666667
std      3.286335   35974.528026
min      1.000000   20000.000000
25%      2.750000   30000.000000
50%      5.000000   50000.000000
75%      6.500000   58750.000000
max     10.000000  120000.000000

In [ ]:
df['Salary'] = df['Salary'] + 5500
df

     Name  Experiance    Salary               Role
0     Raj        10.0  125500.0        ML Engineer
1   Alone         5.0   50500.0  Software Engineer
2     Bob         NaN   60500.0  Software Engineer
3   Kamal         1.0   30500.0        ML Engineer
4  Geetha         2.0       NaN                 HR
5   Steve         7.0   65500.0                 HR
6  Lalith         5.0   25500.0     Data Scientist

In [ ]:
df.rename(columns = {'Name':'Employee'},inplace = True)

In [ ]:
df

  Employee  Experiance    Salary               Role
0      Raj        10.0  125500.0        ML Engineer
1    Alone         5.0   50500.0  Software Engineer
2      Bob         NaN   60500.0  Software Engineer
3    Kamal         1.0   30500.0        ML Engineer
4   Geetha         2.0       NaN                 HR
5    Steve         7.0   65500.0                 HR
6   Lalith         5.0   25500.0     Data Scientist

In [ ]:
df['Role'].value_counts()

Role
ML Engineer          2
Software Engineer    2
HR                   2
Data Scientist       1
Name: count, dtype: int64

In [ ]:
df['Promotion Salary'] = df['Salary'] * 2
df

  Employee  Experiance    Salary               Role  Promotion Salary
0      Raj        10.0  125500.0        ML Engineer          251000.0
1    Alone         5.0   50500.0  Software Engineer          101000.0
2      Bob         NaN   60500.0  Software Engineer          121000.0
3    Kamal         1.0   30500.0        ML Engineer           61000.0
4   Geetha         2.0       NaN                 HR               NaN
5    Steve         7.0   65500.0                 HR          131000.0
6   Lalith         5.0   25500.0     Data Scientist           51000.0

# Data Cleaning

In [ ]:
Null = df.isnull().sum()
Null.name = 'Sum'
Null

Employee            0
Experiance          1
Salary              1
Role                0
Promotion Salary    1
Name: Sum, dtype: int64

In [ ]:
df.dropna()

  Employee  Experiance    Salary               Role  Promotion Salary
0      Raj        10.0  125500.0        ML Engineer          251000.0
1    Alone         5.0   50500.0  Software Engineer          101000.0
3    Kamal         1.0   30500.0        ML Engineer           61000.0
5    Steve         7.0   65500.0                 HR          131000.0
6   Lalith         5.0   25500.0     Data Scientist           51000.0

In [ ]:
df.dropna(how = 'any')
# or use 'all'

  Employee  Experiance    Salary               Role  Promotion Salary
0      Raj        10.0  125500.0        ML Engineer          251000.0
1    Alone         5.0   50500.0  Software Engineer          101000.0
3    Kamal         1.0   30500.0        ML Engineer           61000.0
5    Steve         7.0   65500.0                 HR          131000.0
6   Lalith         5.0   25500.0     Data Scientist           51000.0

In [ ]:
df

  Employee  Experiance    Salary               Role  Promotion Salary
0      Raj        10.0  125500.0        ML Engineer          251000.0
1    Alone         5.0   50500.0  Software Engineer          101000.0
2      Bob         NaN   60500.0  Software Engineer          121000.0
3    Kamal         1.0   30500.0        ML Engineer           61000.0
4   Geetha         2.0       NaN                 HR               NaN
5    Steve         7.0   65500.0                 HR          131000.0
6   Lalith         5.0   25500.0     Data Scientist           51000.0

In [ ]:
df.fillna(0)

  Employee  Experiance    Salary               Role  Promotion Salary
0      Raj        10.0  125500.0        ML Engineer          251000.0
1    Alone         5.0   50500.0  Software Engineer          101000.0
2      Bob         0.0   60500.0  Software Engineer          121000.0
3    Kamal         1.0   30500.0        ML Engineer           61000.0
4   Geetha         2.0       0.0                 HR               0.0
5    Steve         7.0   65500.0                 HR          131000.0
6   Lalith         5.0   25500.0     Data Scientist           51000.0

In [ ]:
df['Experiance'].fillna(df['Experiance'].mean())

0    10.0
1     5.0
2     5.0
3     1.0
4     2.0
5     7.0
6     5.0
Name: Experiance, dtype: float64

In [ ]:
df['Salary'].fillna(df['Salary'].median())

0    125500.0
1     50500.0
2     60500.0
3     30500.0
4     55500.0
5     65500.0
6     25500.0
Name: Salary, dtype: float64

In [ ]:
df.fillna(method = 'bfill')

/tmp/ipython-input-3673297803.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill')

  Employee  Experiance    Salary               Role  Promotion Salary
0      Raj        10.0  125500.0        ML Engineer          251000.0
1    Alone         5.0   50500.0  Software Engineer          101000.0
2      Bob         1.0   60500.0  Software Engineer          121000.0
3    Kamal         1.0   30500.0        ML Engineer           61000.0
4   Geetha         2.0   65500.0                 HR          131000.0
5    Steve         7.0   65500.0                 HR          131000.0
6   Lalith         5.0   25500.0     Data Scientist           51000.0

In [ ]:
df['Promotion Salary'] = df['Promotion Salary'].apply(lambda x: x*2 if x<100000 else x)
df['Experiance'] = df['Experiance'] + 1
df

  Employee  Experiance    Salary               Role  Promotion Salary
0      Raj        12.0  125500.0        ML Engineer          251000.0
1    Alone         7.0   50500.0  Software Engineer          101000.0
2      Bob         NaN   60500.0  Software Engineer          121000.0
3    Kamal         3.0   30500.0        ML Engineer          122000.0
4   Geetha         4.0       NaN                 HR               NaN
5    Steve         9.0   65500.0                 HR          131000.0
6   Lalith         7.0   25500.0     Data Scientist          102000.0

# Importing Files

In [ ]:
path = '/content/drive/MyDrive/Data_Set/healthcare_dataset.csv'
data = pd.read_csv(path)
data

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [ ]:
data[['Date of Admission','Discharge Date']] = data[['Date of Admission','Discharge Date']].apply(pd.to_datetime)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.4+ MB