In [1]:
import pandas as pd
pd.__version__

'2.2.2'

In [2]:
lst = [1,2,3,4,5,6]
series = pd.Series(lst)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
empty = pd.Series([])
empty

Series([], dtype: object)

In [5]:
diff_index = pd.Series(['p','y','t','h','o','n'],index = [11,12,13,14,15,16])

print(diff_index)

11    p
12    y
13    t
14    h
15    o
16    n
dtype: object

# Pandas With Dictionary **Series**

In [6]:
dict_series = pd.Series({1:'p',2:'q',3:'r',4:'s'})
print(dict_series)

1    p
2    q
3    r
4    s
dtype: object

In [7]:
dict_series[2]

'q'

# Intro to Dataframe

In [8]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [9]:
lst = [1,2,3,4,5,6,7]
df = pd.DataFrame(lst)
print(df)

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [10]:
lst2 =[[1,2,3,4,5],[8,6,5,3,2]]
sample = pd.DataFrame(lst2)
print(sample)

   0  1  2  3  4
0  1  2  3  4  5
1  8  6  5  3  2

Now Work with Dictionary

In [11]:
a = [{'a':2,'b':4,'c':6},{'a':3,'b':6,'c':9}]
dict_a = pd.DataFrame(a)
print(dict_a)

   a  b  c
0  2  4  6
1  3  6  9

In [12]:
b = {'Roll No.':pd.Series([1,2,3,4,5,6]),'Maths':pd.Series([43,67,98,73,67]),'Science':pd.Series([98,72,83,93,49])}
ds = pd.DataFrame(b)
ds

   Roll No.  Maths  Science
0         1   43.0     98.0
1         2   67.0     72.0
2         3   98.0     83.0
3         4   73.0     93.0
4         5   67.0     49.0
5         6    NaN      NaN

# **Reading CSV**

In [13]:
path = '/content/drive/MyDrive/Data_Set/car_sales_data.xlsx'
dataset = pd.read_excel(path)
print(dataset)

         Car Model Fuel Type  Engine Size (cc)  Mileage (kmpl)  \
0       Honda City    Petrol              1498            17.8
1    Hyundai Creta    Diesel              1598            19.5
2     Maruti Swift    Petrol              1197            21.2
3       Tata Nexon    Diesel              1497            22.4
4  Toyota Fortuner    Diesel              2755            14.2
5    Mahindra Thar    Petrol              1997            15.2
6       Kia Seltos    Petrol              1353            16.8
7    Maruti Baleno    Petrol              1197            21.4
8    Ford EcoSport    Diesel              1498            20.9
9   Renault Duster    Petrol              1498            16.5

   Car Price (INR) Transmission Type
0          1200000         Automatic
1          1400000            Manual
2           750000            Manual
3          1050000         Automatic
4          3000000         Automatic
5          1500000            Manual
6          1250000         Automatic
7           800000            Manual
8          1100000            Manual
9          1150000            Manual

In [14]:
print(dataset.columns)

Index(['Car Model', 'Fuel Type', 'Engine Size (cc)', 'Mileage (kmpl)',
       'Car Price (INR)', 'Transmission Type'],
      dtype='object')

In [15]:
dataset.shape

(10, 6)

In [16]:
dataset.size

60

In [17]:
dataset.head(10)

,Car Model,Fuel Type,Engine Size (cc),Mileage (kmpl),Car Price (INR),Transmission Type
0,Honda City,Petrol,1498,17.8,1200000,Automatic
1,Hyundai Creta,Diesel,1598,19.5,1400000,Manual
2,Maruti Swift,Petrol,1197,21.2,750000,Manual
3,Tata Nexon,Diesel,1497,22.4,1050000,Automatic
4,Toyota Fortuner,Diesel,2755,14.2,3000000,Automatic
5,Mahindra Thar,Petrol,1997,15.2,1500000,Manual
6,Kia Seltos,Petrol,1353,16.8,1250000,Automatic
7,Maruti Baleno,Petrol,1197,21.4,800000,Manual
8,Ford EcoSport,Diesel,1498,20.9,1100000,Manual
9,Renault Duster,Petrol,1498,16.5,1150000,Manual

In [18]:
dataset.tail()

,Car Model,Fuel Type,Engine Size (cc),Mileage (kmpl),Car Price (INR),Transmission Type
5,Mahindra Thar,Petrol,1997,15.2,1500000,Manual
6,Kia Seltos,Petrol,1353,16.8,1250000,Automatic
7,Maruti Baleno,Petrol,1197,21.4,800000,Manual
8,Ford EcoSport,Diesel,1498,20.9,1100000,Manual
9,Renault Duster,Petrol,1498,16.5,1150000,Manual

In [19]:
dataset.describe()

       Engine Size (cc)  Mileage (kmpl)  Car Price (INR)
count         10.000000       10.000000     1.000000e+01
mean        1608.800000       18.590000     1.320000e+06
std          461.701154        2.874196     6.347353e+05
min         1197.000000       14.200000     7.500000e+05
25%         1389.000000       16.575000     1.062500e+06
50%         1498.000000       18.650000     1.175000e+06
75%         1573.000000       21.125000     1.362500e+06
max         2755.000000       22.400000     3.000000e+06

In [20]:
path1 = '/content/drive/MyDrive/Data_Set/healthcare_dataset.csv'
data = pd.read_csv(path1)
print(data)

                    Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281306          328         Urgent
1               Medicare    33643.327287          265      Emergency
2                  Aetna    27955.096079          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317814          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797307          316       Elective
55497   UnitedHealthcare    27620.764717          347         Urgent
55498           Medicare    32451.092358          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[55500 rows x 15 columns]

In [21]:
data.head(55500)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [22]:
data.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

# replace(to_replace = ,value = )

In [23]:
dataset.head(10)

,Car Model,Fuel Type,Engine Size (cc),Mileage (kmpl),Car Price (INR),Transmission Type
0,Honda City,Petrol,1498,17.8,1200000,Automatic
1,Hyundai Creta,Diesel,1598,19.5,1400000,Manual
2,Maruti Swift,Petrol,1197,21.2,750000,Manual
3,Tata Nexon,Diesel,1497,22.4,1050000,Automatic
4,Toyota Fortuner,Diesel,2755,14.2,3000000,Automatic
5,Mahindra Thar,Petrol,1997,15.2,1500000,Manual
6,Kia Seltos,Petrol,1353,16.8,1250000,Automatic
7,Maruti Baleno,Petrol,1197,21.4,800000,Manual
8,Ford EcoSport,Diesel,1498,20.9,1100000,Manual
9,Renault Duster,Petrol,1498,16.5,1150000,Manual

In [24]:
dataset.replace(to_replace = 'Diesel', value = 'EV')

,Car Model,Fuel Type,Engine Size (cc),Mileage (kmpl),Car Price (INR),Transmission Type
0,Honda City,Petrol,1498,17.8,1200000,Automatic
1,Hyundai Creta,EV,1598,19.5,1400000,Manual
2,Maruti Swift,Petrol,1197,21.2,750000,Manual
3,Tata Nexon,EV,1497,22.4,1050000,Automatic
4,Toyota Fortuner,EV,2755,14.2,3000000,Automatic
5,Mahindra Thar,Petrol,1997,15.2,1500000,Manual
6,Kia Seltos,Petrol,1353,16.8,1250000,Automatic
7,Maruti Baleno,Petrol,1197,21.4,800000,Manual
8,Ford EcoSport,EV,1498,20.9,1100000,Manual
9,Renault Duster,Petrol,1498,16.5,1150000,Manual

In [25]:
mark = '/content/drive/MyDrive/Data_Set/marksheet.csv'
marks = pd.read_csv(mark)
marks.head(250)

      id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81       62     49
1      2    Lemmie    Male   15       B       29       41       17     40
2      3     Danya  Female   14       C       12       87       16     96
3      4     Denna  Female   14       B       15       53       82     33
4      5   Jocelin    Male   14       A       43        6        3     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15       25     10
246  247       Rog  Female   13       B        1        4       68     65
247  248      Kaia    Male   15       B       93       48       82     44
248  249      Anni  Female   14       B       35       73       66     59
249  250  Fernande    Male   15       B       50        8       80     78

[250 rows x 9 columns]

In [26]:
marks.shape

(250, 9)